<?php
    require_once "Contract.php";

    class VIPContract extends Contract {
        protected $restaurant;
        protected $car;

        public function __construct($singOn, $description, $fee, $restaurant, $car)
        {
            parent::__construct($singOn, $description, $fee);
            $this->restaurant = $restaurant;
            $this->car = $car;
        }

        public function getDescription()
        {
            return parent::getDescription(); // TODO: Change the autogenerated stub
        }

        /**
         * @return mixed
         */
        public function getRestaurant()
        {
            return $this->restaurant;
        }

        /**
         * @return mixed
         */
        public function getCar()
        {
            return $this->car;
        }
    }
?>